# Generated by Django 2.2.4 on 2019-09-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('pid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id', models.IntegerField()),
                ('imageId', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('category', models.CharField(max_length=10)),
                ('monthlySales', models.IntegerField()),
            ],
        ),
    ]
