# Generated by Django 2.2.4 on 2020-01-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('oily', models.CharField(max_length=1)),
                ('dry', models.CharField(max_length=1)),
                ('sensitive', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imageId', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('category', models.CharField(max_length=10)),
                ('monthlySales', models.IntegerField()),
                ('ingredients', models.ManyToManyField(related_name='product_ingredient', to='item.Ingredient')),
            ],
        ),
    ]
