# Generated by Django 2.2.4 on 2019-09-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True)),
                ('imageId', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('category', models.CharField(max_length=10)),
                ('monthlySales', models.IntegerField()),
            ],
        ),
    ]
